varnish:
  build: containers/varnish
  links:
    - 'httpd:wordpress'
  ports:
    - "8000:80"
  volumes:
    - './containers/varnish/default.vcl:/etc/varnish/default.vcl'
httpd:
  build: containers/wordpress
  links: 
    - memcache
    - db
  ports:
    - "80:80"
  environment:
    DB_NAME: wordpress
    DB_USER: "dev"
    DB_PASS: "dev"
    DB_PORT: 3306
    DB_HOST: "**LinkMe**"
  volumes:
    - './containers/wordpress/wp-content:/var/www/html/wp-content'
    - './containers/wordpress/config/wp-config.php:/var/www/html/wp-config.php'
memcache:
  image: memcached
db:
  image: tutum/mysql:5.5
  volumes:
    - './containers/wordpress/db_backups/wordpress.sql:/wordpress.sql'
  environment:
    MYSQL_PASS: "dev"
    MYSQL_USER: "dev"
    STARTUP_SQL: '/wordpress.sql'
