apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: production
  name: mysql-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jbpt
        name: mysql
    spec:
      containers:
        - name: mysql
          image: tutum/mysql:5.5
          imagePullPolicy: Always
          resources:
            requests:
              memory: 100Mi
              cpu: 400m
            limits:
              memory: 100Mi
              cpu: 500m
          ports:
          - containerPort: 3306
          env:
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: database
                  key: password
            - name: MYSQL_USER
              value: wordpress
